#!/usr/bin/env ruby

puts "Hello, from a ruby extension!"

args = ARGV

puts args

if args.include?("--exit-code")
  exit_code_index = args.index("--exit-code") + 1
  puts "Exiting with code #{args[exit_code_index].to_i}"
  exit(args[exit_code_index].to_i)
end
